**1. Importing the libraries**

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px 
import plotly.io as pio 
pio.renderers.default = "svg"

**2. Importing the dataset**

In [2]:
dataset= pd.read_csv('Zomato_Mumbai_Dataset.csv',delimiter='|')

In [3]:
dataset

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Mumbai,First International Financial Centre-- Bandra ...,https://www.zomato.com/mumbai/hitchki-bandra-k...,1,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mumbai,Mahim,https://www.zomato.com/mumbai/baba-falooda-mah...,1,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Mumbai,Juhu,https://www.zomato.com/mumbai/chin-chin-chu-ju...,1,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/butterfly-high-b...,1,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/bkc-dive-bandra-...,1,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...,...,...,...
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Mumbai,Kandivali West,https://www.zomato.com/mumbai/hari-om-snack-ba...,99,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Mumbai,Lower Parel,https://www.zomato.com/mumbai/pitaburg-lower-p...,99,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Mumbai,Kandivali West,https://www.zomato.com/mumbai/uncha-otlawala-1...,99,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Mumbai,Malad West,https://www.zomato.com/mumbai/mandarin-panda-m...,99,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**3. Getting Basic Information about the Dataset**

In [4]:
dataset.shape

(15081, 12)

In [5]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 15081 entries, 0 to 15080
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             15081 non-null  str
 1   PRICE            15080 non-null  str
 2   CUSINE_CATEGORY  15079 non-null  str
 3   CITY             15080 non-null  str
 4   REGION           15080 non-null  str
 5   URL              15080 non-null  str
 6   PAGE NO          15080 non-null  str
 7   CUSINE TYPE      15080 non-null  str
 8   TIMING           15015 non-null  str
 9   RATING_TYPE      14070 non-null  str
 10  RATING           15080 non-null  str
 11  VOTES            15080 non-null  str
dtypes: str(12)
memory usage: 1.4 MB

In [6]:
dataset.describe()

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
count,15081,15080,15079,15080,15080,15080,15080,15080,15015,14070,15080,15080
unique,12720,67,3183,2,241,13823,944,23,2551,31,35,1124
top,NAME,400,CUSINE_CATEGORY,Mumbai,REGION,URL,PAGE NO,Quick Bites,11am to 11pm(Mon-Sun),Average,-,-
freq,942,2042,942,14138,942,942,942,5262,1192,5112,2360,2360

**4_Cleaning the Dataset**

**a.Removing the redundunt rows of data**

In [7]:
wrong_data = dataset['PAGE NO'] == 'PAGE NO' 
dataset[wrong_data]

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
31,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
47,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
63,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
79,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
...,...,...,...,...,...,...,...,...,...,...,...,...
15000,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15016,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15032,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15048,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15064,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES

In [8]:
## Performing Negation of the wrong dataset and then storing the correct data back in the raw_df DataFrame 
## This permamnently remove the wrong data from the original dataframe 
dataset = dataset[~wrong_data]

In [9]:
dataset

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Mumbai,First International Financial Centre-- Bandra ...,https://www.zomato.com/mumbai/hitchki-bandra-k...,1,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mumbai,Mahim,https://www.zomato.com/mumbai/baba-falooda-mah...,1,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Mumbai,Juhu,https://www.zomato.com/mumbai/chin-chin-chu-ju...,1,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/butterfly-high-b...,1,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/bkc-dive-bandra-...,1,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...,...,...,...
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Mumbai,Kandivali West,https://www.zomato.com/mumbai/hari-om-snack-ba...,99,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Mumbai,Lower Parel,https://www.zomato.com/mumbai/pitaburg-lower-p...,99,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Mumbai,Kandivali West,https://www.zomato.com/mumbai/uncha-otlawala-1...,99,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Mumbai,Malad West,https://www.zomato.com/mumbai/mandarin-panda-m...,99,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dataset.drop(['URL', 'PAGE NO', 'CITY'], axis = 1, inplace=True)

In [11]:
dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
dataset.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

**b. Removing the Null Records**

In [13]:
dataset.isnull().sum()

NAME                  0
PRICE                 1
CUSINE_CATEGORY       2
REGION                1
CUSINE TYPE           1
TIMING               66
RATING_TYPE        1011
RATING                1
VOTES                 1
dtype: int64

In [14]:
 # Checking for a null row 
dataset[dataset['PRICE'].isnull()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Droping the above row from the dataset
dataset = dataset.drop(labels=15080, axis=0)

In [16]:
dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am(Mon-Sun)",Good,3.5,267
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121

In [17]:
dataset.fillna('NA', inplace=True)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am(Mon-Sun)",Good,3.5,267
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121

In [18]:
# Confirming all the null records are correct 
dataset.isnull().sum()

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
dtype: int64

**c. Converting the DataTypes of numerical columns to numeric dataype**

In [19]:
dataset['RATING'].value_counts()

RATING
-          2360
3.5        1094
3.4        1036
3.6         960
NEW         953
3.3         926
3.7         917
3.2         801
3.8         782
3.1         734
3.0         622
3.9         596
2.9         409
4.0         408
2.8         309
4.1         298
4.2         199
2.7         170
4.3         148
4.4          99
2.6          77
Opening      57
4.5          46
2.5          39
4.6          32
2.4          26
4.7          13
2.3          10
2.1           5
4.8           4
2.2           4
4.9           2
1.8           1
2.0           1
Name: count, dtype: int64

In [20]:
# Replacing the text values with '0' 
 
dataset['RATING'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\1020083532.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: str

In [21]:
# Checking for text values in the column before converting it to numeric datatype 
dataset['VOTES'].value_counts()

VOTES
-       2360
NEW      953
4        364
5        320
6        288
        ...
754        1
914        1
944        1
861        1
1249       1
Name: count, Length: 1123, dtype: int64

In [22]:
# Replacing the text values with '0' 
 
dataset['VOTES'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\485613283.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['VOTES'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

0        3529
1        1723
2         337
3        1200
4        5995
         ...
15075     267
15076      64
15077      99
15078      29
15079     121
Name: VOTES, Length: 14138, dtype: str

In [23]:
print(dataset.columns)

Index(['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'TIMING',
       'RATING_TYPE', 'RATING', 'VOTES'],
      dtype='str')

In [24]:
# Convert using the capital 'Int64' datatype
dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce').astype('Int64')

In [25]:
print(dataset['PRICE'].unique())
print(dataset['RATING'].unique())
print(dataset['VOTES'].unique())

<IntegerArray>
[1200,  400, 1800, 1000,  800, 1300, 1500,  600, 1400, 1100, 2000,  350,  900,
  700,  500, 1600,  150,  300,  550,  450,  650,  750,  250,  200,  850,  100,
 2500, 1450,  180,  950, 1700, 1900, 2600, 2400, 3000, 1250, 3200,  505, 2200,
 1050, 1650, 1350,   50,  920, 1150, 1550, 3500,  398, 5000,  120,  220,  160,
  340,    5,  480, 2100,  580, 1850,  249,   80, 2300,    0,  360, 3502,  248,
 2700]
Length: 66, dtype: Int64
<StringArray>
[    '4.9',     '4.4',     '4.2',     '4.3',     '4.5',     '4.7',     '4.0',
     '4.6',     '4.1',     '3.9',     '3.8',       '-',     '3.6',     'NEW',
     '3.4',     '3.0',     '3.7',     '4.8',     '3.3',     '3.5',     '3.2',
     '3.1',     '2.7',     '2.5',     '2.8',     '2.6',     '2.3',     '2.9',
     '2.4', 'Opening',     '2.1',     '2.2',     '1.8',     '2.0']
Length: 34, dtype: str
<StringArray>
['3529', '1723',  '337', '1200', '5995', '2042', '3058', '1842', '2797',
 '1876',
 ...
 '1608', '1653',  '702',  '660', '2301',  '754',  '914',  '944',  '861',
 '1249']
Length: 1123, dtype: str

In [26]:
dataset['RATING'] = dataset['RATING'].replace('-', np.nan)
dataset['RATING'] = pd.to_numeric(dataset['RATING'], errors='coerce')

In [27]:
print(dataset['RATING'].unique())

[4.9 4.4 4.2 4.3 4.5 4.7 4.  4.6 4.1 3.9 3.8 nan 3.6 3.4 3.  3.7 4.8 3.3
 3.5 3.2 3.1 2.7 2.5 2.8 2.6 2.3 2.9 2.4 2.1 2.2 1.8 2. ]

In [28]:
import numpy as np

dataset['PRICE'] = dataset['PRICE'].replace('-', np.nan)
dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce')

In [29]:
dataset['VOTES'] = dataset['VOTES'].astype(str).str.replace(',', '')
dataset['VOTES'] = pd.to_numeric(dataset['VOTES'], errors='coerce')

In [30]:
import numpy as np

dataset = dataset.replace('-', np.nan)

dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce')
dataset['RATING'] = pd.to_numeric(dataset['RATING'], errors='coerce')
dataset['VOTES'] = pd.to_numeric(dataset['VOTES'], errors='coerce')

In [31]:
dataset.info()

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  Int64
 2   CUSINE_CATEGORY  14138 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14138 non-null  str
 6   RATING_TYPE      14138 non-null  str
 7   RATING           10768 non-null  float64
 8   VOTES            10768 non-null  float64
dtypes: Int64(1), float64(2), str(6)
memory usage: 1.1 MB

**d. Working with 'Timing' column**

In [32]:
 dataset['TIMING'].value_counts()

TIMING
11am to 11pm(Mon-Sun)                               1192
11am to 12midnight(Mon-Sun)                          632
12noon to 12midnight(Mon-Sun)                        467
11am to 1130pm(Mon-Sun)                              309
10am to 10pm(Mon-Sun)                                267
                                                    ...
9am to 9pm(Mon-Sat),9am to 10pm(Sun)                   1
Closed(Mon),7pm to 1130pm(Tue-Fri),1230pm to ...       1
1230pm to 330pm,730pm to 11pm(Mon),1230pm...           1
12noon to 4pm,730pm to 430am(Mon-Sun)                  1
8am to 11pm,12midnight to 115am(Mon-Sun)               1
Name: count, Length: 2551, dtype: int64

In [33]:
 # Splitting the column and storing it in temp_dataset dataframe  
 
temp_dataset = dataset['TIMING'].str.split("(", n = 1, expand = True) 
temp_dataset

                                     0                                 1
0                      12noon to 130am                          Mon-Sun)
1                           2pm to 1am                          Mon-Sun)
2                        12noon to 1am                          Mon-Sun)
3                      12noon to 130am                          Mon-Sun)
4                        1130am to 1am                          Mon-Sun)
...                                ...                               ...
15075  8am to 11pm,12midnight to 115am                          Mon-Sun)
15076                    11am to 230am                          Mon-Sun)
15077                     11am to 11pm  Mon,Tue,Wed,Thu,Sun),11am to ...
15078                    9am to 1230AM                          Mon-Sun)
15079       12noon to 330pm,7pm to 1am                          Mon-Sun)

[14138 rows x 2 columns]

In [34]:
# Assigning the columns back to the raw_df dataframe 

dataset['TIMING'] = temp_dataset[0] 
dataset['DAYS_OPEN'] = temp_dataset[1] 
dataset.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun)
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun)
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun)
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun)
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun)

In [35]:
 # Removing the bracket character from Days column 
 
dataset['DAYS_OPEN'] = dataset['DAYS_OPEN'].str.replace(r'\)', '', regex=True)
dataset.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun

In [36]:
 # Checking for Null records in DAYS_OPEN column 
 
dataset.isnull().sum()

NAME                  0
PRICE                 0
CUSINE_CATEGORY       0
REGION                0
CUSINE TYPE           0
TIMING                0
RATING_TYPE           0
RATING             3370
VOTES              3370
DAYS_OPEN           160
dtype: int64

In [37]:
import numpy as np

dataset.replace('NA', np.nan, inplace=True)

dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce')
dataset['RATING'] = pd.to_numeric(dataset['RATING'], errors='coerce')
dataset['VOTES'] = pd.to_numeric(dataset['VOTES'], errors='coerce')

In [38]:
import numpy as np

dataset.replace(['-', 'NA'], np.nan, inplace=True)

dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce')
dataset['RATING'] = pd.to_numeric(dataset['RATING'], errors='coerce')
dataset['VOTES'] = pd.to_numeric(dataset['VOTES'], errors='coerce')

In [39]:
dataset.info()
dataset[['PRICE','RATING','VOTES']].head(10)

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  Int64
 2   CUSINE_CATEGORY  14137 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14073 non-null  str
 6   RATING_TYPE      13128 non-null  str
 7   RATING           10768 non-null  float64
 8   VOTES            10768 non-null  float64
 9   DAYS_OPEN        13978 non-null  str
dtypes: Int64(1), float64(2), str(7)
memory usage: 1.2 MB

   PRICE  RATING   VOTES
0   1200     4.9  3529.0
1    400     4.4  1723.0
2   1800     4.2   337.0
3   1000     4.3  1200.0
4   1200     4.4  5995.0
5    800     4.2  2042.0
6   1300     4.5  3058.0
7   1500     4.7  1842.0
8    600     4.0  2797.0
9   1800     4.7  1876.0

In [40]:
import numpy as np
import pandas as pd

dataset['RATING'] = dataset['RATING'].replace(['NA', '-', ''], np.nan)

dataset['RATING'] = pd.to_numeric(dataset['RATING'], errors='coerce')

In [41]:
dataset.info()

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  Int64
 2   CUSINE_CATEGORY  14137 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14073 non-null  str
 6   RATING_TYPE      13128 non-null  str
 7   RATING           10768 non-null  float64
 8   VOTES            10768 non-null  float64
 9   DAYS_OPEN        13978 non-null  str
dtypes: Int64(1), float64(2), str(7)
memory usage: 1.2 MB

In [42]:
dataset['RATING'].unique()

array([4.9, 4.4, 4.2, 4.3, 4.5, 4.7, 4. , 4.6, 4.1, 3.9, 3.8, nan, 3.6,
       3.4, 3. , 3.7, 4.8, 3.3, 3.5, 3.2, 3.1, 2.7, 2.5, 2.8, 2.6, 2.3,
       2.9, 2.4, 2.1, 2.2, 1.8, 2. ])

In [43]:
print(dataset['PRICE'].unique())
print(dataset['VOTES'].unique())

<IntegerArray>
[1200,  400, 1800, 1000,  800, 1300, 1500,  600, 1400, 1100, 2000,  350,  900,
  700,  500, 1600,  150,  300,  550,  450,  650,  750,  250,  200,  850,  100,
 2500, 1450,  180,  950, 1700, 1900, 2600, 2400, 3000, 1250, 3200,  505, 2200,
 1050, 1650, 1350,   50,  920, 1150, 1550, 3500,  398, 5000,  120,  220,  160,
  340,    5,  480, 2100,  580, 1850,  249,   80, 2300,    0,  360, 3502,  248,
 2700]
Length: 66, dtype: Int64
[3529. 1723.  337. ...  944.  861. 1249.]

In [44]:
print(dataset[['PRICE','RATING','VOTES']].dtypes)

PRICE       Int64
RATING    float64
VOTES     float64
dtype: object

In [45]:
import numpy as np
import pandas as pd

dataset.replace(['NA', '-'], np.nan, inplace=True)

dataset['PRICE'] = pd.to_numeric(dataset['PRICE'], errors='coerce')
dataset['VOTES'] = pd.to_numeric(
    dataset['VOTES'].astype(str).str.replace(',', ''),
    errors='coerce'
)

print(dataset[['PRICE','RATING','VOTES']].dtypes)

PRICE       Int64
RATING    float64
VOTES     float64
dtype: object

In [46]:
print(dataset['PRICE'].unique()[:20])
print(dataset['VOTES'].unique()[:20])

<IntegerArray>
[1200,  400, 1800, 1000,  800, 1300, 1500,  600, 1400, 1100, 2000,  350,  900,
  700,  500, 1600,  150,  300,  550,  450]
Length: 20, dtype: Int64
[3529. 1723.  337. 1200. 5995. 2042. 3058. 1842. 2797. 1876. 2092. 3191.
 5805. 1510. 1552. 3283. 1088.  881.  898.  688.]

In [47]:
dataset['RATING'].unique()

array([4.9, 4.4, 4.2, 4.3, 4.5, 4.7, 4. , 4.6, 4.1, 3.9, 3.8, nan, 3.6,
       3.4, 3. , 3.7, 4.8, 3.3, 3.5, 3.2, 3.1, 2.7, 2.5, 2.8, 2.6, 2.3,
       2.9, 2.4, 2.1, 2.2, 1.8, 2. ])

In [48]:
dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\4066949127.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [49]:
dataset['RATING'].fillna(dataset['RATING'].mean(), inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\59188723.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(dataset['RATING'].mean(), inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [50]:
dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\4066949127.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [51]:
dataset['RATING'].fillna(0, inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\3459868921.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(0, inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [52]:
dataset['RATING'].fillna(3.5, inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\2213393037.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(3.5, inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [53]:
dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\4066949127.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING'].fillna(dataset['RATING'].median(), inplace=True)

0        4.9
1        4.4
2        4.2
3        4.3
4        4.4
        ...
15075    3.5
15076    3.7
15077    3.4
15078    3.5
15079    3.7
Name: RATING, Length: 14138, dtype: float64

In [60]:
dataset.fillna(0, inplace=True)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267.0,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am,Good,3.7,64.0,Mon-Sun
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99.0,"Mon,Tue,Wed,Thu,Sun,11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM,Good,3.5,29.0,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am",Good,3.7,121.0,Mon-Sun

In [61]:
dataset.fillna('NA', inplace=True)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267.0,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am,Good,3.7,64.0,Mon-Sun
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99.0,"Mon,Tue,Wed,Thu,Sun,11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM,Good,3.5,29.0,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am",Good,3.7,121.0,Mon-Sun

In [62]:
 # Checking info of all the columns 
 
dataset.info()

<class 'pandas.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  str
 1   PRICE            14138 non-null  Int64
 2   CUSINE_CATEGORY  14138 non-null  str
 3   REGION           14138 non-null  str
 4   CUSINE TYPE      14138 non-null  str
 5   TIMING           14138 non-null  str
 6   RATING_TYPE      14138 non-null  str
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  float64
 9   DAYS_OPEN        14138 non-null  str
dtypes: Int64(1), float64(2), str(7)
memory usage: 1.7 MB

**e. Removing the restaurant records whose Rating or Votes is 0**

In [63]:
# Finding those restaurant whose has 0 Rating or Votes 
 
useless_data = (dataset['RATING'] == 0.0) | (dataset['VOTES'] == 0) 
dataset[useless_data]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
32,Hotel Annapoorna Refreshments,400,"Maharashtrian,Mughlai,Chinese",Ghansoli,Quick Bites,1030am to 1230AM,Not rated,0.0,0.0,Mon-Sun
34,Biryani 9,600,"Biryani,North Indian",Near Andheri East Station,none,11am to 3am,NA,0.0,0.0,Mon-Sun
36,D Fusion Flavours,350,Chinese,Goregaon East,none,"12noon to 330pm,7pm to 3am",NA,0.0,0.0,Mon-Sun
39,Nation Tadka,400,"North Indian,South Indian,Chinese,Fast Food",Worli,none,12noon to 1230AM,Not rated,0.0,0.0,Mon-Sun
83,Link Way Restaurant,500,"North Indian,Chinese",Jogeshwari,Quick Bites,"12noon to 4pm,8pm to 1am",Not rated,0.0,0.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14998,Foodies House,0,Chinese,Goregaon East,none,12noon to 4am,NA,0.0,0.0,Mon-Sun
14999,Khansama,0,Biryani,Lower Parel,none,12noon to 3am,NA,0.0,0.0,Mon-Sun
15010,Earth Cafe @ Waterfield,800,"Cafe,Healthy Food,Italian,Pizza,Beverages",Linking Road-- Bandra West,Café,10am to 10pm,NA,0.0,0.0,"Mon-Thu,10am to 11pm(Fri-Sun"
15023,How About Some Cream,200,Beverages,Mumbai Central,Beverage Shop,12noon to 3am,NA,0.0,0.0,Mon-Sun
15046,Food And Taste Theory,800,"Continental,Italian",Phoenix Marketcity-- Kurla,Casual Dining,9am to 12midnight,NA,0.0,0.0,"Mon-Fri,9am to 1230AM(Sat-Sun"

In [64]:
## Performing Negation of the useless dataset and then storing the correct data back in the raw_df DataFrame 
## This permamnently remove the wrong data from the original dataframe 
 
dataset = dataset[~useless_data]

**f. Working on 'RATING_TYPE' Column**

In [65]:
 # Checking the unique values in the column 
 
dataset['RATING_TYPE'].value_counts()

RATING_TYPE
Average          5111
Good             4330
Very Good        1137
Excellent          95
Poor               47
Veľmi dobré         6
Skvělá volba        4
Dobrze              4
Bardzo dobrze       3
Muito Bom           2
Bom                 2
Buono               2
İyi                 2
Bueno               2
Ortalama            2
Průměr              2
Priemer             2
Dobré               2
Promedio            2
Velmi dobré         1
Excelente           1
Çok iyi             1
Baik                1
Média               1
Skvělé              1
Biasa               1
Sangat Baik         1
Muy Bueno           1
Media               1
Name: count, dtype: int64

In [66]:
# Translating the texts into proper English text
dataset['RATING_TYPE'].replace(to_replace='Excelente', value='Excellent', inplace=True)
dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré', 'Bardzo dobrze', 'Muy Bueno', 'Velmi dobré'], value='Very Good', inplace=True)
dataset['RATING_TYPE'].replace(to_replace=['Skvělá volba', 'Dobrze', 'Bueno', 'Buono', 'Dobré', 'Bom', 'Skvělé'], value='Good', inplace=True)
dataset['RATING_TYPE'].replace(to_replace=['Priemer', 'Média', 'Çok iyi'], value='Average', inplace=True)
dataset['RATING_TYPE'].replace(to_replace=['Průměr', 'Promedio', 'Ortalama', 'Muito Bom', 'İyi'], value='Poor', inplace=True)
dataset['RATING_TYPE'].replace(to_replace=['Baik', 'Biasa', 'Media', 'Sangat Baik'], value='Very Poor', inplace=True)

C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace='Excelente', value='Excellent', inplace=True)
C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré', 'Bardzo dobrze', 'Muy Bueno', 'Velmi dobré'], value='Very Good', inplace=True)
C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace=['Skvělá volba', 'Dobrze', 'Bueno', 'Buono', 'Dobré', 'Bom', 'Skvělé'], value='Good', inplace=True)
C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace=['Priemer', 'Média', 'Çok iyi'], value='Average', inplace=True)
C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace=['Průměr', 'Promedio', 'Ortalama', 'Muito Bom', 'İyi'], value='Poor', inplace=True)
C:\Users\lokes\AppData\Local\Temp\ipykernel_12728\47366318.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['RATING_TYPE'].replace(to_replace=['Baik', 'Biasa', 'Media', 'Sangat Baik'], value='Very Poor', inplace=True)

0          Excellent
1          Very Good
2          Very Good
3          Very Good
4        Veľmi dobré
            ...
15075           Good
15076           Good
15077        Average
15078           Good
15079           Good
Name: RATING_TYPE, Length: 10767, dtype: str

In [67]:
 # Checking all the values correctly mapped 
 
dataset['RATING_TYPE'].value_counts()

RATING_TYPE
Average          5111
Good             4330
Very Good        1137
Excellent          95
Poor               47
Veľmi dobré         6
Skvělá volba        4
Dobrze              4
Bardzo dobrze       3
Muito Bom           2
Bom                 2
Buono               2
İyi                 2
Bueno               2
Ortalama            2
Průměr              2
Priemer             2
Dobré               2
Promedio            2
Velmi dobré         1
Excelente           1
Çok iyi             1
Baik                1
Média               1
Skvělé              1
Biasa               1
Sangat Baik         1
Muy Bueno           1
Media               1
Name: count, dtype: int64

**g. Working on 'REGION' Column**

In [68]:
dataset['REGION'].value_counts()

REGION
Mira Road                            405
Malad West                           308
Chembur                              277
Kharghar                             268
Borivali West                        264
                                    ...
Little World Mall-- Kharghar           1
Le Sutra Hotel-- Khar                  1
Maxus Mall-- Bhayandar                 1
Orchard Mall-- Goregaon East           1
Hotel Satkar Residency-- Majiwada      1
Name: count, Length: 237, dtype: int64

In [69]:
# Removing the irrelevant text from the Region column
 
dataset['REGION'] = dataset['REGION'].str.replace('[a-zA-Z].+-- ','',regex=True)

In [70]:
 # Removing the West & East from the Region column 
 
dataset['REGION'] = dataset['REGION'].str.replace(' West| west| East| east','',regex=True)

In [71]:
dataset['REGION'].value_counts()

REGION
Thane                726
Mira Road            412
Andheri              409
Malad                378
Kandivali            377
                    ...
Flea Bazaar Café       3
Majiwada               3
Panvel                 2
CBD Belapur            1
Girgaon Chowpatty      1
Name: count, Length: 101, dtype: int64

In [72]:
# Replacing small regions with known region names
dataset['REGION'] = dataset['REGION'].str.replace('4 Bungalows|7 Andheri|Azad Nagar|Near Andheri Station|Veera Desai Area', 'Andheri', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Bandra Kurla Complex', 'Bandra', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('CBD-Belapur', 'CBD Belapur', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Girgaon Chowpatty', 'Chowpatty', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Dadar Shivaji Park', 'Dadar', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Flea Bazaar Café|Kamala Mills Compound', 'Lower Parel', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Runwal Green', 'Mulund', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Mumbai CST Area', 'Mumbai Central', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Kopar Khairane|Seawoods|Turbhe|Ulwe', 'Navi Mumbai', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('New Panvel|Old Panvel', 'Panvel', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Kamothe', 'Sion', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Ghodbunder Road|Majiwada', 'Thane', regex=True)

**h. Removing Duplicate records**

In [73]:
 # Finding all the duplicate rows 
 
dataset[dataset.duplicated()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
4064,Sai Sannidhi Restaurant & Bar,1000,"North Indian,Konkan",Dahisar,Casual Dining,11am to 12midnight,Good,3.7,99.0,Mon-Sun
4068,Konkan Katta,400,"Seafood,Maharashtrian,Malwani",Mahakali,Quick Bites,"11am to 330pm,630pm to 1130pm",Good,3.5,181.0,Mon-Sun
4082,Usmaniya Hotel,600,Mughlai,Fort,Casual Dining,1030am to 1130pm,Average,3.2,8.0,Mon-Sun
4083,Gina's Cakes,450,Bakery,Dombivali,none,11am to 11pm,Good,3.5,49.0,Mon-Sun
4084,Konkanastha Lunch Home,400,"Seafood,Malwani",Chakala,Casual Dining,"12noon to 3pm,730pm to 1030pm",Good,3.5,44.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14200,Mezbaan Family Restaurant,350,"Chinese,Mughlai",Mumbra,Dhaba,12noon to 1230AM,Average,2.8,97.0,Mon-Sun
14204,Jyoti Lunch Home,650,"Chinese,North Indian,Seafood,Mughlai",Mulund,Casual Dining,11am to 1230AM,Good,3.5,49.0,Mon-Sun
14253,On Toes,900,"Italian,North Indian,Chinese",Malad,Casual Dining,"12noon to 3pm,7pm to 1230AM",Good,3.6,76.0,Mon-Sun
14761,Frosty Farm,400,"Ice Cream,Desserts,Fast Food",Malad,Dessert Parlor,1pm to 1215AM,Good,3.6,120.0,Mon-Sun
14928,Shree Manu Sagar,300,"North Indian,Chinese,Indian",Ghansoli,Quick Bites,"1130am to 415pm,7pm to 1215AM",Average,3.3,51.0,Mon-Sun

In [74]:
 # Dropping all the duplicate rows 
 
dataset = dataset.drop_duplicates()

**4. Copying the cleaned data into a new DataFrame**

In [75]:
zomato_dataset = dataset.copy()

In [76]:
 zomato_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Andheri,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267.0,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali,Quick Bites,11am to 230am,Good,3.7,64.0,Mon-Sun
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99.0,"Mon,Tue,Wed,Thu,Sun,11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor,9am to 1230AM,Good,3.5,29.0,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad,none,"12noon to 330pm,7pm to 1am",Good,3.7,121.0,Mon-Sun

**5. Performing Exploratory Data Analysis
Q1) How many restaurants are in Mumbai for each type of cuisine?**

In [77]:
fig = px.histogram(zomato_dataset, x='CUSINE TYPE', color='CUSINE TYPE',  
             title= 'No. of Restaurants by Cuisine Type',  
             labels={'CUSINE TYPE':'Cuisine Type'}) 
 
fig.show(renderer="colab")

**Q2) What are the percentage of restaurants by Rating Type in Mumbai?**

In [78]:
rating_type_dataset = zomato_dataset['RATING_TYPE'].value_counts().reset_index() 
rating_type_dataset.rename(columns={'index':'RATING TYPE', 'RATING_TYPE':'COUNT OF RESTAURANTS'}, inplace=True) 
rating_type_dataset

   COUNT OF RESTAURANTS  count
0               Average   4979
1                  Good   4246
2             Very Good   1134
3             Excellent     95
4                  Poor     46
5           Veľmi dobré      6
6          Skvělá volba      4
7                Dobrze      4
8         Bardzo dobrze      3
9             Muito Bom      2
10                  Bom      2
11                Buono      2
12                  İyi      2
13                Bueno      2
14             Ortalama      2
15               Průměr      2
16              Priemer      2
17                Dobré      2
18             Promedio      2
19          Velmi dobré      1
20            Excelente      1
21              Çok iyi      1
22                 Baik      1
23                Média      1
24               Skvělé      1
25                Biasa      1
26          Sangat Baik      1
27            Muy Bueno      1
28                Media      1

In [79]:
print(rating_type_dataset.columns)

Index(['COUNT OF RESTAURANTS', 'count'], dtype='str')

In [80]:
rating_type_dataset = zomato_dataset['RATING_TYPE'].value_counts().reset_index() 
rating_type_dataset.rename(columns={'index':'RATING TYPE', 'RATING_TYPE':'COUNT OF RESTAURANTS'}, inplace=True) 
rating_type_dataset

   COUNT OF RESTAURANTS  count
0               Average   4979
1                  Good   4246
2             Very Good   1134
3             Excellent     95
4                  Poor     46
5           Veľmi dobré      6
6          Skvělá volba      4
7                Dobrze      4
8         Bardzo dobrze      3
9             Muito Bom      2
10                  Bom      2
11                Buono      2
12                  İyi      2
13                Bueno      2
14             Ortalama      2
15               Průměr      2
16              Priemer      2
17                Dobré      2
18             Promedio      2
19          Velmi dobré      1
20            Excelente      1
21              Çok iyi      1
22                 Baik      1
23                Média      1
24               Skvělé      1
25                Biasa      1
26          Sangat Baik      1
27            Muy Bueno      1
28                Media      1

In [81]:
fig = px.pie(rating_type_dataset, names='COUNT OF RESTAURANTS', values='count', color='COUNT OF RESTAURANTS',  
        title='Percentage of Restaurants by Rating Type').update_traces(textposition='inside', textinfo='percent+label')
fig.show(renderer="colab")

**Q3) Which are the Top 10 highest rated Seafood Restaurant in Mumbai?**

In [82]:
seafood_dataset = zomato_dataset[zomato_dataset['CUSINE_CATEGORY'].str.contains('Seafood')] 
seafood_dataset.sort_values(by='RATING',ascending=False).head(10)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
7104,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",Khar,Bar,"12noon to 4pm,7pm to 3am",Excellent,4.7,564.0,Mon-Sun
76,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",Thane,Casual Dining,1130am to 1130pm,Excellent,4.6,350.0,Mon-Sun
13685,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",Kharghar,Casual Dining,"11am to 345pm,7pm to 1145pm",Excellent,4.6,209.0,Mon-Sun
9954,Pi Bar and Kitchen,1600,"Continental,European,Italian,Seafood,Pizza,Des...",Andheri,Bar,"12noon to 6pm,7pm to 12midnight",Excellent,4.5,2068.0,Mon-Sun
884,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining,11am to 11pm,Excellent,4.5,178.0,Mon-Sun
12433,Quarter Canteen,1100,"North Indian,Seafood,Chinese",Bandra,Casual Dining,"12noon to 330pm,7pm to 1am",Excellent,4.5,573.0,Mon-Sun
3380,Peco Peco,700,"Chinese,Seafood,Asian",Powai,none,"12noon to 330pm,7pm to 1230AM",Excellent,4.5,497.0,Mon-Sun
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",Bandra,Casual Dining,12noon to 1am,Excellent,4.5,100.0,Mon-Sun
915,Monis Bar and Restaurant,1000,"North Indian,Chinese,Continental,Seafood,Bever...",Thane,Casual Dining,"1130am to 330pm,6pm to 1130pm",Very Good,4.4,662.0,Mon-Sun
8890,Hardeep Punjab,1100,"North Indian,Chinese,Mughlai,Seafood",Sion,Casual Dining,11am to 1am,Very Good,4.4,871.0,Mon-Sun

**Q4) Which is the best Food Truck in Mumbai?**

In [83]:
foodtruck_dataset = zomato_dataset[zomato_dataset['CUSINE TYPE'] == 'Food Truck'] 
foodtruck_dataset.sort_values(by='RATING',ascending=False).head(2)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
262,Dumpling Delights,200,Momos,Matunga,Food Truck,430pm to 930pm,Very Good,4.3,212.0,Mon-Sun
1017,Street Food Co.,250,"Fast Food,Chinese",Virar,Food Truck,6pm to 3am,Very Good,4.1,274.0,Mon-Sun

**Q5) Which places have the highest rated restaurant for each Cuisine Type in Mumbai?**

In [84]:
 # Assuming restaurants having rating above 4.5 
 
highest_rated_dataset = zomato_dataset[zomato_dataset['RATING'] >= 4.5] 
highest_rated_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
6,Persian Darbar,1300,"Biryani,North Indian,Chinese,Mughlai",Marol,Casual Dining,10am to 3am,Excellent,4.5,3058.0,Mon-Sun
7,Tanatan,1500,Modern Indian,Juhu,Casual Dining,12noon to 130am,Excellent,4.7,1842.0,Mon-Sun
9,Plum by Bent Chair,1800,Asian,Lower Parel,Casual Dining,12noon to 1am,Excellent,4.7,1876.0,Mon-Sun
10,Angrezi Dhaba,1500,"North Indian,Chinese,Thai,European",Dadar,Bar,12noon to 1am,Excellent,4.5,2092.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14228,Zaika Crave - Club Aquaria,1300,"North Indian,Continental,Chinese,Desserts",Borivali,Casual Dining,"11am to 330pm,7pm to 1130pm",Excellent,4.5,1302.0,"Mon,Tue,Wed..."
14234,Cone Culture,250,European,Kharghar,Casual Dining,Closed,Excellent,4.6,492.0,"Mon,12noon to 11pm(Tue-Sun"
15007,Dessertino,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor,11am to 12midnight,Excellent,4.8,184.0,Mon-Sun
15051,Tick-eat,800,"North Indian,Italian,Chinese,Mexican,Lebanese",Mulund,Casual Dining,"1130am to 330pm,7pm to 1130pm",Excellent,4.5,754.0,Mon-Sun
15056,Daftar Goregaon,750,"Pizza,Chinese,North Indian,Beverages",Goregaon,Casual Dining,12noon to 1130pm,Excellent,4.6,388.0,Mon-Sun

In [85]:
fig = px.histogram(highest_rated_dataset, x='REGION', color='CUSINE TYPE',  
             title= 'No. of Best Restaurant for each Cuisine Type by Places').update_xaxes(categoryorder="total descending")

fig.show(renderer="colab")

**Q6) What is the Avg Price Distibution of highest rated restaurant for each Cuisine Type in Mumbai?**

In [86]:
highest_rated_price_dataset = highest_rated_dataset.groupby(by=['REGION', 'CUSINE TYPE'])['PRICE'].mean().reset_index() 
highest_rated_price_dataset.head()

    REGION     CUSINE TYPE   PRICE
0  Andheri             Bar  1600.0
1  Andheri            Café   800.0
2  Andheri   Casual Dining  1175.0
3  Andheri  Dessert Parlor   300.0
4  Andheri          Lounge  1700.0

In [87]:
fig = px.scatter(highest_rated_price_dataset, x="REGION", y="PRICE", color="CUSINE TYPE", symbol="CUSINE TYPE",  
           title=' Avg Price Distibution of High rated restaurant for each Cuisine Type').update_traces(marker_size=10)
 
fig.show(renderer="colab")

**Q7) Which areas have a large number of Chinese Restaurant Market?**

In [88]:
chinese_dataset = zomato_dataset[zomato_dataset['CUSINE_CATEGORY'].str.contains('Chinese')] 
chinese_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar,1130am to 1am,Veľmi dobré,4.4,5995.0,Mon-Sun
5,Flea Bazaar Café,800,"American,Asian,Street Food,North Indian,Luckno...",Lower Parel,Café,12noon to 1am,Very Good,4.2,2042.0,Mon-Sun
6,Persian Darbar,1300,"Biryani,North Indian,Chinese,Mughlai",Marol,Casual Dining,10am to 3am,Excellent,4.5,3058.0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15071,Lucknow Zaika,500,"North Indian,Chinese",Kurla,Quick Bites,12noon to 2am,Average,2.6,36.0,Mon-Sun
15072,Zuha's Kitchen,400,"Chinese,North Indian,Mughlai",Mumbai Central,Quick Bites,"12noon to 4pm,730pm to 430am",Average,3.3,13.0,Mon-Sun
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Andheri,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267.0,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali,Quick Bites,11am to 230am,Good,3.7,64.0,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad,none,"12noon to 330pm,7pm to 1am",Good,3.7,121.0,Mon-Sun

In [89]:
chinese_rest_dataset = chinese_dataset.groupby(by='REGION').agg({'NAME': 'count', 'PRICE': 'mean'}).rename(columns={'NAME': 'COUNT OF RESTAURANTS'})
chinese_rest_dataset = chinese_rest_dataset.sort_values('COUNT OF RESTAURANTS', ascending=False).head(25)
chinese_rest_dataset.head()

           COUNT OF RESTAURANTS       PRICE
REGION
Thane                       371  590.983827
Andheri                     313  627.316294
Mira Road                   224  553.348214
Malad                       186  604.032258
Goregaon                    163  548.773006

In [90]:
chinese_rest_dataset = chinese_dataset.groupby('REGION').agg({'NAME': 'count', 'PRICE': 'mean'}).reset_index()
chinese_rest_dataset.rename(columns={'NAME': 'COUNT OF RESTAURANTS'}, inplace=True)

In [91]:
fig = px.bar(chinese_rest_dataset, x='REGION', y='COUNT OF RESTAURANTS', color='PRICE', 
             title='No. of Chinese Restaurants by Region and Price')
fig.show(renderer="colab")

**Q8) Is there a relation between Price and Rating by each Cuisine Type?**

In [92]:
price_rating_dataset = zomato_dataset.groupby(['CUSINE TYPE', 'RATING'])['PRICE'].mean().reset_index() 
price_rating_dataset

    CUSINE TYPE  RATING       PRICE
0        Bakery     2.7       400.0
1        Bakery     2.8  285.714286
2        Bakery     2.9  328.571429
3        Bakery     3.0       300.0
4        Bakery     3.1  369.117647
..          ...     ...         ...
278        none     4.3  683.333333
279        none     4.4       555.0
280        none     4.5       420.0
281        none     4.6       687.5
282        none     4.7       350.0

[283 rows x 3 columns]

In [93]:
fig = px.line(price_rating_dataset, y="PRICE", x="RATING",color='CUSINE TYPE') 
fig.show(renderer="colab")

**Q9) Is there a relation between Region and Price?**

In [94]:
region_price_dataset = zomato_dataset.groupby(['REGION'])['PRICE'].mean().reset_index() 
region_price_dataset

        REGION       PRICE
0       Airoli  452.287582
1      Alibaug       665.0
2    Ambernath       514.0
3      Andheri  562.506596
4       Bandra  724.945946
..         ...         ...
75    Vikhroli  480.434783
76  Vile Parle  464.457831
77       Virar  452.027027
78      Wadala       427.5
79       Worli  537.012987

[80 rows x 2 columns]

In [95]:
fig = px.scatter(region_price_dataset, x="REGION", y="PRICE").update_traces(marker_size=8) 
fig.show(renderer="colab")

**Q10) Find the list of Affordable Restaurants?**

**The criteria for Affordable Restaurants would be:**

1) Low Price 2) High Rated

First step will be to find the restaurants with average cost 1/4th the average cost of most expensive restaurant in our dataframe.

Let me explain:-The most expensive restaurant has an average meal cost= 6000. We'll try to stay economical and only pick the
restaurants that are 1/4th of 6000

In [96]:
max_price = zomato_dataset['PRICE'].max() 
one_fourth_price = max_price/4 
one_fourth_price

np.float64(1250.0)

In [97]:
 # Finding list of restaurants that have price less than and equal to 1/4th of the max price i.e Finding Cheap Restaurant
 
aff_rest_dataset = zomato_dataset[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE']] 
aff_rest_dataset = aff_rest_dataset[aff_rest_dataset['PRICE'] <= 1250] 
aff_rest_dataset.sort_values(by='PRICE', inplace=True) 
aff_rest_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
6137,Sanjog Wine N Dine,5,"North Indian,Chinese",Thane,Casual Dining
2925,Jab We Eat,50,"South Indian,North Indian,Maharashtrian,Fast Food",Girgaum,none
9598,Ho5 Store,50,Fast Food,Matunga,none
10996,Pandurang Wada Pav And Sandwich Centre,100,Street Food,Goregaon,Quick Bites
3328,Gurukrupa Sandwich And Frankie Corner,100,"Rolls,Fast Food",Sion,none
...,...,...,...,...,...
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar
17,Ustaadi,1200,"Asian,Biryani,Chinese,North Indian,Mughlai,Mid...",Mumbai Central,Casual Dining
7301,SamBar Pub & Kitchen,1250,"Finger Food,South Indian,North Indian",Khar,Pub
6045,Fabelle at The Chocolate Boutique - ITC Grand ...,1250,Desserts,Parel,Dessert Parlor
964,Bijoli Grill,1250,Bengali,Powai,Casual Dining

Now, we'll merge the aff_rest_df with highrate_rest_df to obtain the intersection i.e the list of Affordable Restaurants !!

In [98]:
# Finding the highest rated list of restaurants 
 
highrate_rest_dataset = zomato_dataset[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE','RATING']] 
highrate_rest_dataset = highrate_rest_dataset[highrate_rest_dataset['RATING'] >= 4.5] 
highrate_rest_dataset.sort_values(by='PRICE', inplace=True) 
highrate_rest_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,RATING
1502,Cake Centre-The Dessert Maker,150,Desserts,Mohammad Ali Road,Dessert Parlor,4.6
807,Moussestruck,200,Desserts,Andheri,none,4.5
763,Curry And Combos Twist,200,"North Indian,Chinese",Andheri,Quick Bites,4.5
14234,Cone Culture,250,European,Kharghar,Casual Dining,4.6
725,Belo Pops,300,"Ice Cream,Desserts,Beverages",Andheri,none,4.5
...,...,...,...,...,...,...
8887,Drifters Tap Station,2000,"North Indian,Continental,European,American",Bandra,Casual Dining,4.5
1786,Global Fusion,2000,"Chinese,Japanese,Asian,North Indian",Worli,Fine Dining,4.6
5335,Mia Cucina,2000,Italian,Bandra,Casual Dining,4.5
12625,House of Mandarin,2100,"Chinese,Sushi,Asian",Bandra,Casual Dining,4.5
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",Bandra,Casual Dining,4.5

In [99]:
highrate_aff_dataset = pd.merge(aff_rest_dataset, highrate_rest_dataset, how='inner', on=['NAME', 'REGION']) 
highrate_aff_dataset = highrate_aff_dataset[['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']] 
highrate_aff_dataset.rename(columns={'NAME':'NAME', 'PRICE_x':'PRICE', 'CUSINE_CATEGORY_x':'CUSINE_CATEGORY',  
                                'REGION':'REGION', 'CUSINE TYPE_x':'CUSINE TYPE'},inplace=True)

In [100]:
 # Affordable Restaurants with low price and high rating  
 
highrate_aff_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
0,Cake Centre-The Dessert Maker,150,Desserts,Mohammad Ali Road,Dessert Parlor
1,Curry And Combos Twist,200,"North Indian,Chinese",Andheri,Quick Bites
2,Moussestruck,200,Desserts,Andheri,none
3,Cone Culture,250,European,Kharghar,Casual Dining
4,Dessertino,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor
...,...,...,...,...,...
60,Culinary Tales,1200,"Chinese,European,Continental,Salad,Italian,Pizza",Andheri,Casual Dining
61,Wild Dining Restaurant,1200,"North Indian,Continental,Mexican,Chinese",Andheri,Casual Dining
62,The Joker Bistro,1200,"North Indian,Chinese,Continental",CBD Belapur,Casual Dining
63,Invento,1200,"Chinese,Fast Food,North Indian,Italian,Mexican",Lower Parel,Casual Dining
64,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining

**Q10) Find the list of most Reliable Restaurants?**

**The criteria for most Reliable Restaurants would be:**

1) Low Price 2) High Rated 3) Large No. of Votes

First step will be to find the restaurants with Votes greater than Mean of Votes

In [101]:
mean_votes = zomato_dataset['VOTES'].mean() 
mean_votes

np.float64(177.2656679624538)

In [102]:
# Finding list of restaurants that have Votes greater than and equal to  Mean of Vote 
 
mean_rest_dataset = zomato_dataset[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'VOTES']] 
mean_rest_dataset = mean_rest_dataset[mean_rest_dataset['VOTES'] > 177] 
mean_rest_dataset.sort_values(by='VOTES', inplace=True) 
mean_rest_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,VOTES
99,Appetite - Resto Bar,700,"North Indian,Chinese",Powai,Casual Dining,178.0
12267,Buddha Bowl,1000,"Asian,Healthy Food",Bandra,none,178.0
2193,Mumbai Darbar,850,"North Indian,Chinese,Seafood",Lower Parel,Casual Dining,178.0
11211,Soul Curry,800,"Chinese,North Indian,Malwani,Mughlai,Biryani",Bhandup,Casual Dining,178.0
2392,Jain Sweet & Farsan House,200,"Street Food,Beverages,Fast Food,Mithai",Goregaon,Quick Bites,178.0
...,...,...,...,...,...,...
8539,Leopold Cafe & Bar,1600,"American,Chinese,Mughlai,Italian",Colaba,Casual Dining,7327.0
1251,Joey's Pizza,800,Pizza,Malad,Quick Bites,7350.0
5337,Chili's American Grill & Bar,1400,"American,Mexican,Burger,Tex-Mex",Powai,Casual Dining,7377.0
3751,Prithvi Cafe,700,"Cafe,Fast Food",Juhu,Café,8000.0
8897,Candies,700,"Cafe,Italian,North Indian,Desserts",Bandra,Café,10217.0

**These are the most reliable, highest rated and affordable restaurants**

We obtain this dataframe by simply taking the intersection of highrate_aff_df & mean_rest_df

This dataframe obtained below shows the restaurants whose:

_Cost is below_ **1250**,
_Rating is above_ **4.5**,
_Votes are above_ **177**,

In [103]:
reliable_rest_dataset = pd.merge(mean_rest_dataset, highrate_aff_dataset, how='inner', on=['NAME', 'REGION']) 
reliable_rest_dataset = reliable_rest_dataset[['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']] 
reliable_rest_dataset.rename(columns={'NAME':'NAME', 'PRICE_x':'PRICE', 'CUSINE_CATEGORY_x':'CUSINE_CATEGORY',  
                                'REGION':'REGION', 'CUSINE TYPE_x':'CUSINE TYPE'},inplace=True)

In [104]:
 reliable_rest_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
0,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining
1,Fresh Food Co.,500,"Continental,Healthy Food,Salad,Beverages,Desse...",Santacruz,none
2,Dessertino,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor
3,Invento,1200,"Chinese,Fast Food,North Indian,Italian,Mexican",Lower Parel,Casual Dining
4,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",Kharghar,Casual Dining
5,Regano's,600,"Continental,Fast Food,Italian,Desserts",Malad,Casual Dining
6,Big Bang Cuurry,350,"North Indian,Biryani,Rolls",Andheri,none
7,Sandy's Den,1000,"Fast Food,Bar Food",Chembur,Casual Dining
8,Angrezi Patiyalaa,1200,"North Indian,Finger Food,American,Mexican,Chinese",Andheri,Casual Dining
9,Maezo,1000,Modern Indian,Thane,Casual Dining
10,Tossin Pizza,900,"Pizza,Italian,Fast Food",Chembur,Casual Dining
11,Little West Pizza,600,Pizza,Borivali,Quick Bites
12,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",Thane,Casual Dining
13,Moussestruck,200,Desserts,Andheri,none
14,Daftar Goregaon,750,"Pizza,Chinese,North Indian,Beverages",Goregaon,Casual Dining
15,Poetry By Love & Cheesecake,1000,"Cafe,Desserts",Juhu,Café
16,Makhan Singh,800,"North Indian,Chinese,Biryani",Powai,none
17,The Joker Bistro,1200,"North Indian,Chinese,Continental",CBD Belapur,Casual Dining
18,Cone Culture,250,European,Kharghar,Casual Dining
19,Peco Peco,700,"Chinese,Seafood,Asian",Powai,none
20,Shuruwat- Veg Food Journey,600,"Continental,Tea,South Indian,Fast Food,Pizza,N...",Ghatkopar,Casual Dining
21,Justice Cafe and Dine,800,"Cafe,Chinese,Italian,Continental,North Indian,...",Thane,Café
22,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",Khar,Bar
23,Harsh's Bistro,800,"Chinese,Continental",Malad,Casual Dining
24,Quarter Canteen,1100,"North Indian,Seafood,Chinese",Bandra,Casual Dining
25,Culinary Tales,1200,"Chinese,European,Continental,Salad,Italian,Pizza",Andheri,Casual Dining
26,Dum & Curry,700,"Mughlai,North Indian,Chinese",Powai,Quick Bites
27,Curry Culture,800,"North Indian,Biryani,Chinese,Kebab,Mughlai,Asian",Powai,none
28,Belo Pops,300,"Ice Cream,Desserts,Beverages",Andheri,none
29,Tick-eat,800,"North Indian,Italian,Chinese,Mexican,Lebanese",Mulund,Casual Dining
30,Coppetto Artisan Gelato,350,"Ice Cream,Desserts",Bandra,Dessert Parlor
31,Zaika Restaurant & Party Hall,1000,"North Indian,Chinese,Beverages",Bhayandar,Casual Dining
32,Shaollin Temple,1000,"Chinese,Thai",CBD Belapur,Casual Dining
33,Spice Republic,1200,"Cafe,Continental,Mediterranean,Mexican,Italian...",Borivali,Café
34,Aquafire Restaurant,1100,"North Indian,Continental,Chinese,Italian",Vile Parle,Casual Dining
35,Rajdhani,950,"Gujarati,Rajasthani,North Indian",Ghatkopar,Casual Dining
36,Wild Dining Restaurant,1200,"North Indian,Continental,Mexican,Chinese",Andheri,Casual Dining
37,Family Tree,800,"Italian,Mexican,North Indian,Chinese,Salad",Thane,Casual Dining
38,Bombay Salad Co.,900,"Salad,Healthy Food,Juices",Bandra,Casual Dining
39,Cafe Monza,1000,"Italian,American,Salad,Mexican",Kharghar,Casual Dining
40,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining
41,Vedge,1000,"Thai,Chinese,North Indian,Mexican,Italian,Asian",Andheri,Casual Dining
42,Joey's Pizza,800,Pizza,Malad,Quick Bites